services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "81:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: development
    expose:
      - "3000"
    env_file:
      - ./frontend/.env
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    expose:
      - "8000"
    env_file:
      - ./backend/.env
    volumes:
      - audio-storage:/app/.audio-storage
    restart: unless-stopped

volumes:
  audio-storage:
